**EXAMPLE: Illustration of Case 1.** We pick a matrix `A` and a vector `y` such that `y` is not in the
range of `A`. Therefore, there is no solution to the matrix equation.

In [32]:
import numpy as np
from numpy.linalg import matrix_rank

A = np.array([[1, 2, 3], [0, 3, 1], [-1, 14, 7]])
A = np.matrix(A)
print(A)

y = np.array([[1], [2], [3]])
y = np.matrix(y)
print(y)

print(matrix_rank(A))
print(matrix_rank(np.concatenate((A, y), axis=1)))

[[ 1  2  3]
 [ 0  3  1]
 [-1 14  7]]
[[1]
 [2]
 [3]]
3
3


**EXAMPLE: Illustration of Case 2.** We pick a matrix `A` and a vector `y` such that `y` is in the range
of `A`, and such that the rank of `A` is equal to the number of unknowns.

In [47]:
from numpy.linalg import inv

A = np.array([[1, 2, 3], [0, 3, 1], [-1, 14, 7]])
A = np.matrix(A)
print("A =", A)
print()

y = np.array([[1], [2], [3]])
y = np.matrix(y)
print("y =", y)
print()

print(matrix_rank(A))
print(matrix_rank(np.concatenate((A, y), axis=1)))
print()

x = inv(A)*y
print("x =", x)
print()

# We also give an example with square matrices:
A = np.array([[1, 2, 3], [0, 3, 1], [-1, 14, 7]])
A = np.matrix(A)
print("A =", A)
print()

y = A * np.matrix(np.array([[1], [1], [1]]))
print("y =", y)
print()

x = inv(A)*y
print("x =", x)
print()

# The last command produces the expected result; that is, the result of the inversion of the matrix. 
# To check that it does what it is supposed to do, we can see that:
print("A * x =", A * x)

# Now if we augment A by one row at the bottom, so it is not square anymore, we get a nonsquare matrix. 
# Let us look at what needs to be done in this case:
A = np.array([[1, 2, 3], [0, 3, 1], [-1, 14, 7], [1, 1, 1]])
A = np.matrix(A)
print("A =", A)
print()

# If we reiterate the previous process, we get:
y = A * np.matrix(np.array([[1], [1], [1]]))
print("y =", y)
print()

# Note that using the inverse command would not work in this case because the matrix A is not square.
x = inv(A)*y
print("x =", x)
print()

A = [[ 1  2  3]
 [ 0  3  1]
 [-1 14  7]]

y = [[1]
 [2]
 [3]]

3
3

x = [[ 3.        ]
 [ 1.14285714]
 [-1.42857143]]

A = [[ 1  2  3]
 [ 0  3  1]
 [-1 14  7]]

y = [[ 6]
 [ 4]
 [20]]

x = [[1.]
 [1.]
 [1.]]

A * x = [[ 6.]
 [ 4.]
 [20.]]
A = [[ 1  2  3]
 [ 0  3  1]
 [-1 14  7]
 [ 1  1  1]]

y = [[ 6]
 [ 4]
 [20]
 [ 3]]



LinAlgError: Last 2 dimensions of the array must be square

**EXAMPLE: Illustration of Case 3.** We first illustrate this case with a square matrix.

In [72]:
from scipy.linalg import null_space

A = np.array([[1, 2, 3, 0], [0, 3, 1, 0], [-1, 14, 7, 0], [0, 0, 0, 0]])
A = np.matrix(A)
print("A =", A)
print()

y = A * np.matrix(np.array([[1], [1], [1], [0]]))
print("y =", y)
print()

x = np.linalg.pinv(A)*y
print("x =", x)
print()

print("A * x =", A * x)
print("A * [0; 0; 0; 1] =", A * np.matrix(np.array([[0], [0], [0], [1]])))
print("A * (x + [0; 0; 0; 100]) =", A * (x +  np.matrix(np.array([[0], [0], [0], [100]]))))

# To investigate the example of a nonsquare matrix, let us consider the following script:
# Define A and y
A = np.array([[1, 2, 3, 4, 5, 6], [2, 3, 4, 5, 6, 7], [3, 4, 5, 6, 7, 8]])
A = np.matrix(A)
print("A =", A)
print()

y = np.array([[21], [27], [33]])
y = np.matrix(y)
print("y =", y)
print()

# Specify an x and verify that it is a solution to Ax = y
x = np.array([1, 1, 1, 1, 1, 1])
x = np.matrix(x)
x = np.transpose(x)
print("x =", x)
print()

y = A * x
print("y =", y)
print()

# Specify a different x and verify that it is a solution
x = np.array([3, 0, 0, 0, 0, 3])
x = np.matrix(x)
x = np.transpose(x)
print("x =", x)
print()

y = A * x
print("y =", y)
print()

# generate a solution using pinv
x = np.linalg.pinv(A)*y
print("x =", x)
print()

# generate vectors in nullspace using null_space function
N = null_space(A)
print("N =", N)
print()
n1 = N[:, 0]
n2 = N[:, 1]
n3 = N[:, 2]
n4 = N[:, 3]

# verify that a linear combination of solutions and null space vectors is still a solution
y = A * np.matrix((np.array(x) + np.array(31*n1) + np.array(202*n2) + np.array(87*n3) + np.array(42*n4)))
print("y =", y)
print()

A = [[ 1  2  3  0]
 [ 0  3  1  0]
 [-1 14  7  0]
 [ 0  0  0  0]]

y = [[ 6]
 [ 4]
 [20]
 [ 0]]

x = [[1.]
 [1.]
 [1.]
 [0.]]

A * x = [[ 6.]
 [ 4.]
 [20.]
 [ 0.]]
A * [0; 0; 0; 1] = [[0]
 [0]
 [0]
 [0]]
A * (x + [0; 0; 0; 100]) = [[ 6.]
 [ 4.]
 [20.]
 [ 0.]]
A = [[1 2 3 4 5 6]
 [2 3 4 5 6 7]
 [3 4 5 6 7 8]]

y = [[21]
 [27]
 [33]]

x = [[1]
 [1]
 [1]
 [1]
 [1]
 [1]]

y = [[21]
 [27]
 [33]]

x = [[3]
 [0]
 [0]
 [0]
 [0]
 [3]]

y = [[21]
 [27]
 [33]]

x = [[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]

N = [[ 0.67422815 -0.10354683  0.10087619  0.02662561]
 [-0.61419879  0.02426005  0.21360898  0.53038138]
 [-0.30190889 -0.37011372 -0.59329795 -0.48878627]
 [ 0.02139574  0.87292598 -0.14038637 -0.19204619]
 [-0.05141042 -0.21481687  0.70184974 -0.40420234]
 [ 0.27189421 -0.20870862 -0.28265058  0.52802782]]

y = [[ 2.28461459e+02  5.82127710e+02 -3.26062992e+03  3.31200999e+03
   2.05165405e+00 -7.38020889e+02]
 [ 2.93736162e+02  7.48449913e+02 -4.19223847e+03  4.25829856e+03
   2.63784092e+00 -9.