<!--BOOK_INFORMATION-->
<img align="left" style="padding-right:10px;" src="images/book_cover.jpg" width="120">

*This notebook contains an excerpt from the [Python Programming And Numerical Methods: A Guide For Engineers And Scientists](); the content is available [on GitHub]().*

*The text is released under the [CC-BY-NC-ND license](https://creativecommons.org/licenses/by-nc-nd/3.0/us/legalcode), and code is released under the [MIT license](https://opensource.org/licenses/MIT). If you find this content useful, please consider supporting the work by [buying the book]()!*

<!--NAVIGATION-->
< [15.2 The Power Method](chapter15.02-The-Power-Method.ipynb) | [Contents](Index.ipynb) | [15.4 Eigenvalues and Eigenvectors in Python](chapter15.04-Eigenvalues-and-Eigenvectors-in-Python.ipynb)  >

# The QR Method

The QR method is a preferred iterative method to find all the eigenvalues of a matrix (but not the eigenvectors at the same time). The idea is based on the following two concepts

1. similar matrices will have the same eigenvalues and associated eigenvectors. Two square matrices $A$ and $B$ are similar if:

 $$A = C^{-1}BC$$

 where $C$ is an invertible matrix. 

2. The QR method is a way to decompose a matrix into two matrices $Q$ and $R$, where $Q$ is an orthogonal matrix, and $R$ is an upper triangular matrix. An orthogonal matrix has the features: $Q^{-1} = Q^T$, which means $Q^{-1}Q=Q^TQ=I$. 

How do we link these two concepts to find the eigenvalues? Let's say we have a matrix $A_1$ whose eigenvalues are to be determined. We can start the first iteration by decomposing it to:

$$A_1 = Q_1R_1$$

If we multiply $R_1$ from the right by $Q_1$, we have a new matrix $A_2 = R_1Q_1$, since $R_1 = Q^{-1}A_1$, therefore, we have:

$$A_2 = Q^{-1}A_1Q_1$$

which means that $A_1$ and $A_2$ are similar, thus having the same eigenvalues and eigenvectors. 

We can repeat the above procedures to decompose $A_2 = Q_2R_2$ and calculate $A_3 = R_2Q_2$. As the iteration goes, we will eventually converge to an upper triangular matrix form: 

$$ A_k = R_kQ_k = \begin{bmatrix}
\lambda_1 & X & \dots & X\\
0 & \lambda_2 & \dots & X\\
& &\dots &\\
0 & 0 & \dots & \lambda_n\\
\end{bmatrix}$$

where the diagonal values are the eigenvalues of the matrix. We won't go into the mathematical details how you get the $Q$ and $R$ from the matrix, but instead, we will use the Python function to directly get the two matrices. 

**TRY IT!** Use the *qr* function in numpy.linalg to decompose matrix $A = \begin{bmatrix}
0 & 2\\
2 & 3\\
\end{bmatrix}$. And verify the results. 

In [1]:
import numpy as np
from numpy.linalg import qr

In [2]:
a = np.array([[0, 2], 
              [2, 3]])

q, r = qr(a)

print('Q:', q)
print('R:', r)

b = np.dot(q, r)
print('QR:', b)

Q: [[ 0. -1.]
 [-1.  0.]]
R: [[-2. -3.]
 [ 0. -2.]]
QR: [[0. 2.]
 [2. 3.]]


**TRY IT!** Use the QR method to get the eigenvalues of matrix $A = \begin{bmatrix}
0 & 2\\
2 & 3\\
\end{bmatrix}$. Do 20 iterations, and print out the 1st, 5th, 10th, and 20th iteration.

In [3]:
a = np.array([[0, 2], 
              [2, 3]])
p = [1, 5, 10, 20]
for i in range(20):
    q, r = qr(a)
    a = np.dot(r, q)
    if i+1 in p:
        print(f'Iteration {i+1}:')
        print(a)

Iteration 1:
[[3. 2.]
 [2. 0.]]
Iteration 5:
[[ 3.99998093  0.00976559]
 [ 0.00976559 -0.99998093]]
Iteration 10:
[[ 4.00000000e+00  9.53674316e-06]
 [ 9.53674316e-06 -1.00000000e+00]]
Iteration 20:
[[ 4.00000000e+00  9.09484250e-12]
 [ 9.09494702e-12 -1.00000000e+00]]


We can see after the 5th iteration, the eigenvalues are converge to the correct ones. 

In next section, we will take a look how to get the eigenvalues and eigenvectors in Python easily using the built-in function. 

<!--NAVIGATION-->
< [15.2 The Power Method](chapter15.02-The-Power-Method.ipynb) | [Contents](Index.ipynb) | [15.4 Eigenvalues and Eigenvectors in Python](chapter15.04-Eigenvalues-and-Eigenvectors-in-Python.ipynb)  >